version: "3"

services:
    nodejs:
        build: 
            context: ./nodejsserver    
        container_name: nodejsserver
        hostname: nodejsserver
        ports: 
            - "3000:3000"
        depends_on:
            - redis
        networks:
            - docker-net
    redis:
        build: 
            context: ./redis
        container_name: redis
        hostname: redis
        ports: 
            - "6379:6379"
        networks:
            - docker-net
    nginx:
        build: 
            context: ./nginx
        container_name: nginx
        hostname: nginx
        ports: 
            - "80:80"
            - "443:443"
        depends_on:
            - nodejs
        networks:
            - docker-net

networks:
    docker-net:
        external: true 